src/Entity/Projet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjetRepository")
 */
class Projet
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez choisir un titre")
     * @Assert\Length(
     *     max="255", maxMessage="Votre titre ne doit pas dépasser {{ limit }} caractères",
     *     min="10", minMessage="Votre titre doit contenir minimum {{ limit }} caractères"
     * )
     */
    private $titre;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Domaine", inversedBy="projets")
     * @Assert\Count(min=1,
     *     minMessage="Vous devez choisir au moins une catégorie")
     */
    private $domaine;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut_inscription;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual(
     *     propertyPath="date_debut_inscription",
     *     message="La date de fin d'inscription doit être supérieure ou égale à la date de début d'inscription"
     * )
     */
    private $date_fin_inscription;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Vous devez rédiger une description")
     * @Assert\Length(
     *     max="5000", maxMessage="La description ne doit pas dépasser {{ limit }} caractères",
     *     min="10", minMessage="La description doit contenir minimum {{ limit }} caractères"
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez saisir une adresse de site")
     * @Assert\Url
     */
    private $website;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThan(
     *     propertyPath="date_fin_inscription",
     *     message="La date du début d'évènement doit être supérieure à la date de la fin d'inscription"
     * )
     */
    private $date_debut_evenement;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual(
     *     propertyPath="date_debut_evenement",
     *     message="La date de fin d'évènement doit être supérieure ou égale à la date de début d'évènement"
     * )
     */
    private $date_fin_evenement;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Image(
     *     mimeTypesMessage="Vérifiez le format de votre image",
     *     maxSize="1M", maxSizeMessage="Attention, votre image est trop lourde"
     * )
     * @Assert\NotBlank(message="Vous devez choisir une image")
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=80)
     * @Assert\NotBlank(message="Vous devez choisir une ville")
     * @Assert\Length(
     *     max="80", maxMessage="Votre saisie ne doit pas dépasser {{ limit }} caractères",
     *     min="2", minMessage="Votre saisie doit contenir minimum {{ limit }} caractères"
     * )
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $pays;

    /**
     * @ORM\Column(type="integer")
     */
    private $Budget;

    /**
     * @ORM\Column(type="integer")
     */
    private $frais;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\File(
     *     maxSize = "1024k",
     *     mimeTypes = {"application/pdf", "application/x-pdf"},
     *     mimeTypesMessage = "Le format du document doit être en PDF"
     * )
     */
    private $document;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="projets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;


    public function __construct()
    {
        $this->domaine = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    /**
     * @return Collection|Domaine[]
     */
    public function getDomaine(): Collection
    {
        return $this->domaine;
    }

    public function addDomaine(Domaine $domaine): self
    {
        if (!$this->domaine->contains($domaine)) {
            $this->domaine[] = $domaine;
        }

        return $this;
    }

    public function removeDomaine(Domaine $domaine): self
    {
        if ($this->domaine->contains($domaine)) {
            $this->domaine->removeElement($domaine);
        }

        return $this;
    }

    public function getDateDebutInscription(): ?\DateTimeInterface
    {
        return $this->date_debut_inscription;
    }

    public function setDateDebutInscription(\DateTimeInterface $date_debut_inscription): self
    {
        $this->date_debut_inscription = $date_debut_inscription;

        return $this;
    }

    public function getDateFinInscription(): ?\DateTimeInterface
    {
        return $this->date_fin_inscription;
    }

    public function setDateFinInscription(\DateTimeInterface $date_fin_inscription): self
    {
        $this->date_fin_inscription = $date_fin_inscription;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(string $website): self
    {
        $this->website = $website;

        return $this;
    }

    public function getDateDebutEvenement(): ?\DateTimeInterface
    {
        return $this->date_debut_evenement;
    }

    public function setDateDebutEvenement(\DateTimeInterface $date_debut_evenement): self
    {
        $this->date_debut_evenement = $date_debut_evenement;

        return $this;
    }

    public function getDateFinEvenement(): ?\DateTimeInterface
    {
        return $this->date_fin_evenement;
    }

    public function setDateFinEvenement(\DateTimeInterface $date_fin_evenement): self
    {
        $this->date_fin_evenement = $date_fin_evenement;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getBudget(): ?int
    {
        return $this->Budget;
    }

    public function setBudget(int $Budget): self
    {
        $this->Budget = $Budget;

        return $this;
    }

    public function getFrais(): ?int
    {
        return $this->frais;
    }

    public function setFrais(int $frais): self
    {
        $this->frais = $frais;

        return $this;
    }

    public function getDocument()
    {
        return $this->document;
    }

    public function setDocument($document): self
    {
        $this->document = $document;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/Iceberg/ProjetController.php
<?php


namespace App\Controller\Iceberg;

use App\Controller\ProjetTrait;
use App\Entity\Domaine;
use App\Entity\Projet;
use App\Entity\User;

use App\Form\ProjetType;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\CountryType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ProjetController
 * @package App\Controller\Iceberg
 */
class ProjetController extends AbstractController
{
    use ProjetTrait;



    #################################################################
    #                                                               #
    #                           APPEL A PROJET                      #
    #                                                               #
    #################################################################

    /**
     * Page Formulaire pour rédiger un appel à projet
     * @IsGranted("ROLE_ORGANISATEUR")
     * @Route("/modifier-mon-projet/{id}", name="projet_ma_modification")
     * @Route("/creer-un-projet",
     *     name="projet_new")
     */
    public function newProjet(Request $request, Projet $projet = null)
    {
        # Récupération d'un organisateur connecté
        $user = $this->getUser();

        if($projet === null) {
            #Création d'un nouvel appel
            $projet = new Projet();
        }

        # Attribution d'un auteur à un nouvel appel
        $projet->setUser($user);

        # Création du formulaire
        $form = $this->createForm(ProjetType::class, $projet);

        # Traitement des données POST (getsion des erreurs)
        $form->handleRequest($request);

        # Si le formulaire est valide

        if($form->isSubmitted() && $form->isValid()) {

            # ########### Gestion des Null ##############
            # Gestion du Null pour "budget"
            $budget = $projet->getBudget();
            if($budget === Null) {
                $projet->setBudget(0);
            }

            # Gestion du Null pour "frais"
            $frais = $projet->getFrais();
            if($frais === Null) {
                $projet->setFrais(0);
            }

            # ########### Upload de l'image ##############
            /**
             * @var UploadedFile $image
             */
            $image = $projet->getImage();

            # Rennomer l'image
            $fileName = $this->slugify($projet->getTitre()).'.'.$image->guessExtension();

            # Déplacer l'image dans le dossier "public/image"
            try {
                $image->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }

            # Mise à jour du nom de l'image
            $projet->setImage($fileName);

            # ################### Upload du PDF ####################
            /**
             * @var UploadedFile $document
             */
            $document = $projet->getDocument();

            if($document != Null) {
                # Rennomer le document
                $docName = $this->slugify($projet->getTitre()).'.'.$document->guessExtension();

                # Déplacer le document dans le dossier "public/PDF"
                try {
                    $document->move(
                        $this->getParameter('documents_directory'),
                        $docName
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                # Mise à jour du nom du document
                $projet->setDocument($docName);
            }


            # Sauvegarde en BDD
            $em = $this->getDoctrine()->getManager();
            $em->persist($projet);
            $em->flush();

            # Notification flash
            $this->addFlash('notice',
                'Votre projet a bien été sauvegardé');

            #Redirection
            return $this->redirectToRoute("default_index");

        } // Fin $form->isSubmitted

        # Rendu vers formProjet.html.twig
        return $this->render('Projet/formProjet.html.twig', [
            'form' => $form->createView()
        ]);
    } ######################## FIN de function newProjet ###########################


    /**
     * Page vue des appels à projet de l'organisateur
     * @IsGranted("ROLE_ORGANISATEUR")
     * @Route("/projets", name="projet_vue")
     */
    public function vueProjets()
    {
        # Récupération des projets dans BDD
        $projets = $this->getDoctrine()
            ->getRepository(Projet::class)
            ->findBy(['user' => $this->getUser()]);

        # Rendu de la vue
        return $this->render('Projet/vueProjets.html.twig', [
            'projets' => $projets
        ]);

    } ################## Fin de function vueProjets ##########################


    /**
     * Suppression des appels à projet de l'organisateur connecté
     * @Route("/supprimer-mon-projet/{id}", name="projet_ma_suppression")
     */
    public function supprimerProjetOrga(Projet $projet, EntityManagerInterface $entityManager)
    {
        # Récupération d'un membre connecté
        $user = $this->getUser();

        $entityManager->remove($projet);
        $entityManager->flush();

        # Rendu de la vue
        return $this->redirectToRoute('projet_vue');

    } ################## Fin de function supprimerProjetOrga ##########################


    /**
     * Suppresion des appels à projets par l'Admin
     * @IsGranted("ROLE_ADMIN")
     * @Route("/supprimer-projet/{id}", name="projet_supprimer")
     */
    public function supprimerProjetAdmin($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $projets = $entityManager->getRepository(Projet::class)->find($id);
        $entityManager->remove($projets);
        $entityManager->flush();

        # Notification
        $this->addFlash('notice',
            'Félicitation, l\'appel à projet a bien été supprimé !');

        # Rendu de la vue
        return $this->redirectToRoute('user_liste_projet');
    } ################## Fin de function supprimerProjetAdmin ##########################


    /**
     * Ajout en favori
     * @Route("/ajouter-favori/{id}", name="projet_ajouter_favori")
     */
    public function newFavori(Projet $projet, EntityManagerInterface $entityManager)
    {
        # Récupération d'un membre connecté
        $user = $this->getUser();
        /** @var User $user */
        $user->addFavori($projet);
        $entityManager->persist($user);
        $entityManager->flush();
        return $this->redirectToRoute('default_index');
    } ################## Fin de function newFavori ##########################

    /**
     * Liste des favoris
     * @Route("/liste_favori", name="projet_liste_favori")
     *
     */
    public function listeFavori()
    {
         # Récupération d'un membre connecté
         $user = $this->getUser();

         # Récupération des favoris du membre connecté
         $favoris= $user->getFavoris();

        # Rendu de la vue
        return $this->render('/Projet/favori.html.twig', [
            'favoris' => $favoris
        ]);
    } ################## Fin de function listeFavori ##########################

    /**
     * Suppresion du favori
     * @Route("/supprimer-favori/{id}", name="projet_supprimer_favori")
     */
    public function supprimerFavori(Projet $projet, EntityManagerInterface $entityManager)
    {
        # Récupération d'un membre connecté
        $user = $this->getUser();
        /** @var User $user */
        $user->removeFavori($projet);
        $entityManager->persist($user);
        $entityManager->flush();
        return $this->redirectToRoute('projet_liste_favori');

    }
}

templates/Projet/favori.html.twig
{% extends "layout.html.twig" %}

{% block page_title %}
   Mes favoris
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block content %}

    <div class="container" style="padding-top:50px;">



        {% include 'Components/_modalProfil.html.twig' %}


        {% if favoris is not empty %}
        {% for favori in favoris %}
            <!-- ##### Card ##### -->
            <div class="titre" class="row">
                <h3 class="linear-gradient">
                    {% for domaine in favori.domaine %}
                        {{ domaine.categorie }}
                    {% endfor %}
                </h3>
            </div>
            <div class="row">
                <div class="col-md-10 no-padding lib-item" data-category="view">
                    <div class="lib-panel">
                        <div class="row box-shadow">
                            <div class="col-md-3">
                                <img class="lib-img-show card-img" src="{{ asset('images/' ~ favori.image ) }}">
                            </div>   <!--{# fin div. col-md-4#}  -->

                            <div class="col-md-8">
                                <div class="lib-row lib-header">
                                    <h4>{{ favori.titre }}</h4>
                                    <div class="lib-header-seperator"></div>
                                </div>
                                <div class="lib-row lib-desc">
                                    <p>{{ favori.description | raw }}</p>
                                    <a href="">{{ favori.user.prenom }} {{ favori.user.nom }}</a>
                                    <a href="{{ path('projet_supprimer_favori', {id: favori.id}) }}"><i class="far fa-trash-alt"></i></a>
                                </div>
                            </div>   <!--{# fin div. col-md-8#} -->
                        </div>    <!--{# div.box shadow #} -->
                    </div>    <!--{# div.lib panel #}  -->
                </div>   <!--{ # div.col md-10 #}  -->
                <div class="col-md-1"></div>
            </div>  <!--{ # div.row #} -->
        {% endfor %}

        {% else %}
            <div class="alert alert-info">Vous n'avez pas encore de favori</div>

        {% endif %}


    </div> {# fin div.container #}


{% endblock %}

templates/Projet/formProjet.html.twig
{% extends "layout.html.twig" %}


{% block page_title %}
    Publiez votre appel à projets
{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css"
          integrity="sha256-AWdeVMUYtwLH09F6ZHxNgvJI37p+te8hJuSMo44NVm0=" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/form.css') }}">
{% endblock %}


{% block final_javascripts %}
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js"
            integrity="sha256-SUaao5Q7ifr2twwET0iyXVy0OVnuFJhGVi5E/dqEiLU=" crossorigin="anonymous"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor.create(document.querySelector('#projet_description'));
        $('.dropify').dropify({
            messages: {
                default: 'Glissez-d&eacute;posez un fichier ici ou cliquez',
                replace: 'Glissez-d&eacute;posez un fichier ou cliquez pour remplacer',
                remove: 'Supprimer',
                error: 'D&eacute;sol&eacute;, le fichier est trop volumineux'
            }
        });
    </script>
{% endblock %}

{% block content %}


    {# BANDEAU#}
    <div id="bigtitle" class="jumbotron">

        {# CARROUSEL #}
        <div class="container">
            <div id="carouselExampleFade" class="carousel slide " data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="size"
                             src="https://www.dax.fr/wp-content/uploads/2019/03/le-conservatoire-de-musique-et-de-danse.jpg"
                             class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img class="size"
                             src="https://www.dax.fr/wp-content/uploads/2019/03/le-conservatoire-de-musique-et-de-danse.jpg"
                             class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img class="size"
                             src="https://www.dax.fr/wp-content/uploads/2019/03/le-conservatoire-de-musique-et-de-danse.jpg"
                             class="d-block w-100" alt="...">
                    </div>
                </div>
            </div>


            {#div enfant jumbotron#}
            <div class="enfant-jumbotron">
                <div class="container">
                    <h1 class="slogan">Un projet ? </h1>
                    <hr class="traitBlanc">
                    <h2 class="accroche">Postez votre appel aux artistes</h2>
                    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                </div>
            </div>
            {#div enfant#}
        </div>
        {# fin carrousel #}


    </div>

    {% include 'Components/_modalProfil.html.twig' %}

    <div class="container effect1" id="#section02">
        {{ form_start(form, {attr:{novalidate: 'novalidate' }}) }}

        {{ form_errors(form) }}
        <!-- TITRE DE L'APPEL -->
        <div class="form-group">

            <div class="col-md-3">

                <h3 class="titre-appel"> {{ form_label(form.titre) }}</h3>
            </div>
            <div class="col-md-8">
                {{ form_widget(form.titre) }}

            </div>

        </div>

        <!-- CATEGORIE -->
        <div class="form-group">
            <div class="col-md-6">
                <h3><label>{{ form_label(form.domaine) }}</label></h3>
            </div>
            <div class="col-md-12 categorie">
                <div class="col-md-4">
                    {% for domaine in form.domaine %}
                        {% if loop.index < 4 %}
                            {{ form_widget(domaine) }}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="col-md-4">
                    {% for domaine in form.domaine %}
                        {% if loop.index < 7 %}
                            {{ form_widget(domaine) }}
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="col-md-4">
                    {% for domaine in form.domaine %}
                        {% if loop.index < 10 %}
                            {{ form_widget(domaine) }}
                        {% endif %}
                    {% endfor %}
                </div>

            </div>
        </div>

        <!-- DATE DEBUT INSCRIPTION -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.dateDebutInscription) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.dateDebutInscription) }}
            </div>
        </div>

        <!-- DATE FIN INSCRIPTION -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.dateFinInscription) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.dateFinInscription) }}
            </div>
        </div>

        <!-- DESCRIPTION -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.description) }}</h3>
            </div>
            <div class="col-md-12">
                {{ form_widget(form.description) }}
            </div>
        </div>


        <!-- SITE WEB -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.website) }}</h3>
            </div>
            <div class="col-md-6">
                {{ form_widget(form.website) }}
            </div>
        </div>


        <!-- DATE DEBUT EVENEMENT -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.dateDebutEvenement) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.dateDebutEvenement) }}
            </div>
        </div>


        <!-- DATE FIN EVENEMENT -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.dateFinEvenement) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.dateFinEvenement) }}
            </div>
        </div>


        <!-- IMAGE -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.image) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.image) }}
            </div>
        </div>


        <!-- VILLE -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.ville) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.ville) }}
            </div>
        </div>


        <!-- PAYS -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.pays) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.pays) }}
            </div>
        </div>


        <!-- BUDGET -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.budget) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.budget) }}
            </div>
        </div>


        <!-- FRAIS -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.frais) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.frais) }}
            </div>
        </div>


        <!-- DOCUMENT PDF -->
        <div class="form-group">
            <div class="col-md-6">
                <h3>{{ form_label(form.document) }}</h3>
            </div>
            <div class="col-md-4">
                {{ form_widget(form.document) }}
            </div>
        </div>


        {{ form_end(form) }}
    </div><!-- /.container -->


{% endblock %}

templates/Projet/formProjetModif.html.twig
{% extends "layout.html.twig" %}

{% set current = '' %}

{% block stylesheets %}
    {{ parent() }}
    {# Dropify CSS CDN #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/css/dropify.min.css" integrity="sha256-AWdeVMUYtwLH09F6ZHxNgvJI37p+te8hJuSMo44NVm0=" crossorigin="anonymous" />
{% endblock %}

{% block final_javascripts %}
    <!-- Dropify -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Dropify/0.2.2/js/dropify.min.js" integrity="sha256-SUaao5Q7ifr2twwET0iyXVy0OVnuFJhGVi5E/dqEiLU=" crossorigin="anonymous"></script>
    <!-- CKEditor 5 -->
    <script src="https://cdn.ckeditor.com/ckeditor5/12.0.0/classic/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create( document.querySelector( '#form_description' ) );
        $('.dropify').dropify({
            messages: {
                default: 'Glissez-d&eacute;posez un fichier ici ou cliquez',
                replace: 'Glissez-d&eacute;posez un fichier ou cliquez pour remplacer',
                remove:  'Supprimer',
                error:   'D&eacute;sol&eacute;, le fichier est trop volumineux'
            }
        });
    </script>
{% endblock %}

{% block content %}
    <ul>
        {% for projet in projets %}
            <!-- ##### Card ##### -->
            <div class="titre" class="row">
                <h3 class="linear-gradient">
                    {% for domaine in projet.domaine %}
                        {{ domaine.categorie }}
                    {% endfor %}
                </h3>
            </div>
            <div class="row">
                <div class="col-md-10 no-padding lib-item" data-category="view">
                    <div class="lib-panel">
                        <div class="row box-shadow">
                            <div class="col-md-3">
                                <img class="lib-img-show card-img" src="{{ asset('images/' ~ projet.image ) }}">
                            </div>   <!--{# fin div. col-md-4#}  -->

                            <div class="col-md-8">
                                <div class="lib-row lib-header">
                                    <h4>{{ projet.titre }}</h4>
                                    <div class="lib-header-seperator"></div>
                                </div>
                                <div class="lib-row lib-desc">
                                    <p>{{ projet.description | raw }}</p>
                                    <a href="">{{ projet.user.prenom }} {{ projet.user.nom }}</a>
                                    {# Modification de mon projet #}
                                    <a href="{{ path('projet_ma_modification', {id: projet.id}) }}" style="color:red">Modifier mon projet</a>
                                    {# Suppresion de mon projet #}
                                    <a href="{{ path('projet_ma_suppression', {id: projet.id}) }}"><i class="far fa-trash-alt"></i></a>
                                </div>
                            </div>   <!--{# fin div. col-md-8#} -->
                        </div>    <!--{# div.box shadow #} -->
                    </div>    <!--{# div.lib panel #}  -->
                </div>   <!--{ # div.col md-10 #}  -->
                <div class="col-md-1"></div>
            </div>  <!--{ # div.row #} -->
        {% endfor %}
    </ul>

{% endblock %}